
version: "3"
services:
    server_proxy:
      image: ${TUNNEL_IMG} 
      command: ["/root/environments/tls/bin/python", "-u", "/root/environments/tls/tunnel.py", "--mode", "server", "--priv_net_addr", "10.0.0.1/24"]
      volumes:
        - ${ROOT_FOLDER}/certs-server:/root/environments/tls/certs
      cap_add:
        - CAP_NET_ADMIN
    client_proxy:
      image: ${TUNNEL_IMG} 
      command: ["/root/environments/tls/bin/python", "-u", "/root/environments/tls/tunnel.py", "--mode", "client", "--server_addr", "server_proxy", "--priv_net_addr", "10.0.0.2/24"]
      volumes:
        - ${ROOT_FOLDER}/certs-client:/root/environments/tls/certs
      cap_add:
        - CAP_NET_ADMIN
    
    
    client_app:
      image: ${APP_IMG} 
      command: ["/bin/ping", "10.0.0.3"]
      cap_add:
        - CAP_NET_ADMIN
    server_app:
      image: ${APP_IMG} 
      command: ["/bin/ping", "10.0.0.4"]
      cap_add:
        - CAP_NET_ADMIN



    mininet:
      image: ${MININET_IMG}
      command: ["/usr/bin/python3", "/root/mnt/topo_tunnel.py", 
          "--prx_srv_container",  "tunnel_server_proxy_1", "--prx_srv_priv_addr", "10.0.0.1/24",
          "--prx_cli_container", "tunnel_client_proxy_1", "--prx_cli_priv_addr", "10.0.0.2/24",
          "--srv_container", "tunnel_server_app_1", "--srv_priv_addr", "10.0.0.3/24",
          "--cli_container", "tunnel_client_app_1", "--cli_priv_addr", "10.0.0.4/24" ]
      cap_add:
        - CAP_NET_ADMIN
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
        - ${ROOT_FOLDER}/mininet:/root/mnt
      pid: "host"
      privileged: true
      tty: true
      stdin_open: true




